name: Go application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-binary:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.22'
    - name: Test
      run: make -C go test
    - name: Build
      run: make -C go build
  build-docker:
    runs-on: ubuntu-latest
    needs: build-binary
    steps:
      - uses: actions/checkout@v6
      - name: Log in to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: ./go
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/go-service:latest
